dist: xenial
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
  global:
    # For functional tests
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - APP_ENV=behat
    - USER_RUNNING_TESTS=www-data

matrix:
    fast_finish: true
    include:
        - name: "CS Check"
          php: 7.3
          env: CHECK_CS=true
        - name: "PHP 7.3 PHPUnit & PHPSpec"
          php: 7.3
        - name: "PHP 7.3 Rest Functional Tests"
          php: 7.3
          env:
            - TEST_CMD="./bin/.travis/run_rest_tests.sh"
            - APP_DEBUG=1
            - SYMFONY_CMD="ez:behat:create-language 'pol-PL' 'Polish (polski)'"
            - USER_RUNNING_TESTS=root
            - PHP_IMAGE=ezsystems/php:7.3-v1
        - name: "PHP 7.3 Symfony Cache integration tests"
          php: 7.3
          env:
            - TEST_CMD="bin/ezbehat --mode=standard --profile=httpCache --suite=symfonycache"
            - WEB_HOST="web"
            - APP_DEBUG=1
        - name: "PHP 7.3 Varnish integration tests"
          php: 7.3
          env:
            - TEST_CMD="bin/ezbehat --mode=standard --profile=httpCache --suite=varnish"
            - APP_DEBUG=1
            - WEB_HOST=varnish
            - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml"
        - name: "PHP 7.3 Varnish integration tests with invalidate token"
          php: 7.3
          env:
            - TEST_CMD="bin/ezbehat --mode=standard --profile=httpCache --suite=varnish"
            - HTTPCACHE_VARNISH_INVALIDATE_TOKEN=TESTTOKEN
            - APP_DEBUG=1
            - WEB_HOST=varnish
            - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/varnish.yml:doc/docker/selenium.yml"

# test only master + stable (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - travis_retry composer selfupdate
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "$TEST_CMD" = "" ] ; then travis_retry composer install --prefer-dist --no-interaction ; fi
    - if [ "$TEST_CMD" != "" ] ; then ./tests/.travis/prepare_for_functional_tests.sh ; fi
    # Execute Symfony command if injected into test matrix
    - if [ "${SYMFONY_CMD}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/console ${SYMFONY_CMD}" ; fi

script:
    - if [ "$TEST_CMD" = "" ] && [ "$CHECK_CS" != "true" ] ; then php vendor/bin/phpunit --coverage-text && php vendor/bin/phpspec run --format=pretty ; fi
    - if [ "$TEST_CMD" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user "$USER_RUNNING_TESTS" app sh -c "$TEST_CMD"  ; fi
    - if [ "$CHECK_CS" = "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
  slack:
    rooms:
      - secure: eO5PnOM9RS8oKQQQo9hlkcxD1whvJThmjWLJzQHN1BDmdqfJ660bBzgQw7d8pKCBVX8rGnSj7AzIYO0XK7T9gRX8YM4cmER4iCR+gl6jiVoI8fu5VhMcW3db4YVLnrDv38v7ZPSdY+T57DXLy45eoqz4D7+03rBqJzvvyVCVoEXzjqbsMQyHbw2UC7eyAChP9G0EVEiWY/D+bEC25KzEhDExXn3aTyIeynmqm5MhAGOM53+xPWf110PqhPcRS/Oeg2LWS0z6+4QyQMc1JgWQ86/ljzG88pjfG3ypIRcgy4tNFBZea2MQ/UnBxlrbeQyYiP1nkVmsuIaVTRLePHwsadCP+XJKe9BN64y8NCgfmG2zOX8e83TVAXsPO4F9iA2xMq7cZ0Qykf1sAj19DeGdEscF3eblQaDWqjfAthxCXNPbQOqH8wGmNGgj296wIBrT2M7W5dbIV2a1bI1PmETTJg82XqksR+Y90GV3vf2Mu+mX5/dRrawmOodMfLO1ZqUlvLZEvdJ0zgDH0enzIFC94+Y1srmtyzRlUVIhTKnAC+AjXkHR8L7uAPJvAmNLtPbzhkJyYBmriQZtM2BOpPp1uIR5nFxvkaVcyks1mNIRIfLVFHrquTL0KenQha6iAS/4kLt7csuLhJuXg+dXwmel6+X6x8AjDcCqbqAwqv9auTo=
    on_success: change
    on_failure: always
    on_pull_requests: false
