language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
          env: CHECK_CS=true

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - travis_retry composer selfupdate
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer install --prefer-dist --no-interaction

script:
    - php vendor/bin/phpunit --coverage-text && php vendor/bin/phpspec run --format=pretty
    - if [ "$CHECK_CS" == "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false
