dist: xenial
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
  global:
    # For functional tests
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - APP_ENV=behat
    - USER_RUNNING_TESTS=www-data

matrix:
    fast_finish: true
    include:
        - name: "CS Check"
          php: 7.3
          env: CHECK_CS=true
        - name: "PHP 7.3 PHPUnit & PHPSpec"
          php: 7.3
        - name: "PHP 7.3 Rest Functional Tests"
          php: 7.3
          env:
            - TEST_CMD="./bin/.travis/run_rest_tests.sh"
            - APP_DEBUG=1
            - SYMFONY_CMD="ez:behat:create-language 'pol-PL' 'Polish (polski)'"
            - USER_RUNNING_TESTS=root
            - PHP_IMAGE=ezsystems/php:7.3-v1
        - name: "PHP 7.3 Symfony Cache tests"
          php: 7.3
          env:
            - TEST_CMD="bin/ezbehat --profile=httpCache --suite=symfonycache"
            - APP_DEBUG=1

# test only master + stable (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - travis_retry composer selfupdate
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "$TEST_CMD" = "" ] ; then travis_retry composer install --prefer-dist --no-interaction ; fi
    - if [ "$TEST_CMD" != "" ] ; then ./tests/.travis/prepare_for_functional_tests.sh ; fi
    # Execute Symfony command if injected into test matrix
    - if [ "${SYMFONY_CMD}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/console ${SYMFONY_CMD}" ; fi

script:
    - if [ "$TEST_CMD" = "" ] && [ "$CHECK_CS" != "true" ] ; then php vendor/bin/phpunit --coverage-text && php vendor/bin/phpspec run --format=pretty ; fi
    - if [ "$TEST_CMD" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user "$USER_RUNNING_TESTS" app sh -c "$TEST_CMD"  ; fi
    - if [ "$CHECK_CS" = "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
  slack:
    rooms:
      - secure: KR/LU//zh93mD8VERbBCU9NWxQmH9QI9NudhII9prcEey41lXXFMVhiSRPL6RHVinvSGVq5JKfxPB6Q+nVjpBJ+lyywV/PfPWPN6iXjYZPVLlk6tzXWj+FpKYBGkBoKLRZqt9xGqRj/yLJLbrZoMELvS+6tR8Jqn+ccKOHU04sPYCEHhkUI6Iiuc5eRjnHUbsYSPMfsT7Qv1yD3TzJLJOjgl9WjUSwBBW4s9rYIPTflhBjFlkAtO45icee6TrDoeO4PGdVE2fBz/tBvCEUTqte1lFDUFA3mbdEVlzlYekO/712YaMZFWOoA2aO/sTozYF+9UXxrAA1xRInBvxcHg8gK4Nt5bTmBcFYKcsNRBJfWxeBvBBwcTIhn6aAIaBsRU/1kY4c2/oTd4jeO5SF60N4RbAqxZ2a0WZR2X4xHimejYXxG+MslnTYkBdIom4rqHFYl1T2q23aVR2u6GOVGaiye0C14ob3iZjRikuRaabThnTHFSa9LoRCzgtpE3h0w+FBWxWPJWYl46xLWxNUcsplg5KNC0vAK7qIIbhj/l2zGnQKON+QqCL/sRY8ge5Nb2FXPrWA4bEfBXU3f44EsyYGFLEQ3v1UM03LAdCCm2qkTyxWgNcHtXaI/7s+McwCeRy6aireZZ7AMJ58rqu/OkPQLpjBGhTyRht4qtYZfHk+4=
    on_success: change
    on_failure: always
    on_pull_requests: false
