dist: xenial
sudo: required

language: php

cache:
    directories:
        - $HOME/.composer/cache/files


env:
  global:
    # For functional tests
    - COMPOSE_FILE="doc/docker/base-dev.yml:doc/docker/selenium.yml"
    - SYMFONY_ENV=behat

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: CHECK_CS=true
        - php: 7.2
        # Functional
        - php: 7.2
          env: TEST_CMD="bin/phpunit -c vendor/ezsystems/ezplatform-rest/phpunit-integration-rest.xml" SYMFONY_CMD="ez:behat:create-language 'pol-PL' 'Polish (polski)'" PHP_IMAGE=ezsystems/php:7.2-v1

# test only master + stable (+ Pull requests)
branches:
    only:
        - master
        - /^\d.\d+$/

before_script:
    - travis_retry composer selfupdate
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [ "$TEST_CMD" = "" ] ; then travis_retry composer install --prefer-dist --no-interaction ; fi
    - if [ "$TEST_CMD" != "" ] ; then ./tests/.travis/prepare_for_functional_tests.sh ; fi
    # Execute Symfony command if injected into test matrix
    - if [ "${SYMFONY_CMD}" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "bin/console ${SYMFONY_CMD}" ; fi

script:
    - if [ "$TEST_CMD" = "" ] ; then php vendor/bin/phpunit --coverage-text && php vendor/bin/phpspec run --format=pretty ; fi
    - if [ "$TEST_CMD" != "" ] ; then cd "$HOME/build/ezplatform"; docker-compose exec --user www-data app sh -c "$TEST_CMD" ; fi
    - if [ "$CHECK_CS" = "true" ]; then phpenv config-rm xdebug.ini && ./vendor/bin/php-cs-fixer fix -v --dry-run --diff --show-progress=estimating; fi

notifications:
    email: false
