parameters:
    ezplatform.http_cache.store.root: "%kernel.cache_dir%/http_cache"
    ezplatform.http_cache.invalidate_token.ttl: 86400
    ezplatform.http_cache.no_vary.routes: ['ezplatform.httpcache.invalidatetoken']
