proxy_client:
    default: varnish
    varnish:
        servers: [$http_cache.purge_servers$]

user_context:
    enabled: true
    hash_cache_ttl: 600
    user_hash_header: X-User-Hash
    session_name_prefix: eZSESSID

tags:
    # Configure tag header for FosHttpCache
    # See docs/using_tags.md for further info on usage
    header: '%ezplatform.http_cache.tags.header%'
